// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rest.proto

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	rest.proto

It has these top-level messages:
	Thing
	Object
	GetThingReq
	GetThingRes
	CreateThingReq
	CreateThingRes
	UpdateThingReq
	UpdateThingRes
	DeleteThingReq
	DeleteThingRes
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Thing struct {
	Id     string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name   string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Object *Object `protobuf:"bytes,4,opt,name=object" json:"object,omitempty"`
}

func (m *Thing) Reset()                    { *m = Thing{} }
func (m *Thing) String() string            { return proto.CompactTextString(m) }
func (*Thing) ProtoMessage()               {}
func (*Thing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Thing) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Thing) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Thing) GetObject() *Object {
	if m != nil {
		return m.Object
	}
	return nil
}

type Object struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value int32  `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
}

func (m *Object) Reset()                    { *m = Object{} }
func (m *Object) String() string            { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()               {}
func (*Object) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Object) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Object) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type GetThingReq struct {
	ThingID string `protobuf:"bytes,1,opt,name=thingID" json:"thingID,omitempty"`
}

func (m *GetThingReq) Reset()                    { *m = GetThingReq{} }
func (m *GetThingReq) String() string            { return proto.CompactTextString(m) }
func (*GetThingReq) ProtoMessage()               {}
func (*GetThingReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetThingReq) GetThingID() string {
	if m != nil {
		return m.ThingID
	}
	return ""
}

type GetThingRes struct {
	Status      int32  `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Thing       *Thing `protobuf:"bytes,3,opt,name=thing" json:"thing,omitempty"`
}

func (m *GetThingRes) Reset()                    { *m = GetThingRes{} }
func (m *GetThingRes) String() string            { return proto.CompactTextString(m) }
func (*GetThingRes) ProtoMessage()               {}
func (*GetThingRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetThingRes) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetThingRes) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetThingRes) GetThing() *Thing {
	if m != nil {
		return m.Thing
	}
	return nil
}

type CreateThingReq struct {
	Thing *Thing `protobuf:"bytes,1,opt,name=thing" json:"thing,omitempty"`
}

func (m *CreateThingReq) Reset()                    { *m = CreateThingReq{} }
func (m *CreateThingReq) String() string            { return proto.CompactTextString(m) }
func (*CreateThingReq) ProtoMessage()               {}
func (*CreateThingReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateThingReq) GetThing() *Thing {
	if m != nil {
		return m.Thing
	}
	return nil
}

type CreateThingRes struct {
	Status      int32  `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	ThingID     string `protobuf:"bytes,3,opt,name=thingID" json:"thingID,omitempty"`
}

func (m *CreateThingRes) Reset()                    { *m = CreateThingRes{} }
func (m *CreateThingRes) String() string            { return proto.CompactTextString(m) }
func (*CreateThingRes) ProtoMessage()               {}
func (*CreateThingRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CreateThingRes) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateThingRes) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateThingRes) GetThingID() string {
	if m != nil {
		return m.ThingID
	}
	return ""
}

type UpdateThingReq struct {
	Thing *Thing `protobuf:"bytes,1,opt,name=thing" json:"thing,omitempty"`
}

func (m *UpdateThingReq) Reset()                    { *m = UpdateThingReq{} }
func (m *UpdateThingReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateThingReq) ProtoMessage()               {}
func (*UpdateThingReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UpdateThingReq) GetThing() *Thing {
	if m != nil {
		return m.Thing
	}
	return nil
}

type UpdateThingRes struct {
	Status      int32  `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
}

func (m *UpdateThingRes) Reset()                    { *m = UpdateThingRes{} }
func (m *UpdateThingRes) String() string            { return proto.CompactTextString(m) }
func (*UpdateThingRes) ProtoMessage()               {}
func (*UpdateThingRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UpdateThingRes) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdateThingRes) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type DeleteThingReq struct {
	ThingID string `protobuf:"bytes,1,opt,name=thingID" json:"thingID,omitempty"`
}

func (m *DeleteThingReq) Reset()                    { *m = DeleteThingReq{} }
func (m *DeleteThingReq) String() string            { return proto.CompactTextString(m) }
func (*DeleteThingReq) ProtoMessage()               {}
func (*DeleteThingReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *DeleteThingReq) GetThingID() string {
	if m != nil {
		return m.ThingID
	}
	return ""
}

type DeleteThingRes struct {
	Status      int32  `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
}

func (m *DeleteThingRes) Reset()                    { *m = DeleteThingRes{} }
func (m *DeleteThingRes) String() string            { return proto.CompactTextString(m) }
func (*DeleteThingRes) ProtoMessage()               {}
func (*DeleteThingRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *DeleteThingRes) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DeleteThingRes) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Thing)(nil), "Thing")
	proto.RegisterType((*Object)(nil), "Object")
	proto.RegisterType((*GetThingReq)(nil), "GetThingReq")
	proto.RegisterType((*GetThingRes)(nil), "GetThingRes")
	proto.RegisterType((*CreateThingReq)(nil), "CreateThingReq")
	proto.RegisterType((*CreateThingRes)(nil), "CreateThingRes")
	proto.RegisterType((*UpdateThingReq)(nil), "UpdateThingReq")
	proto.RegisterType((*UpdateThingRes)(nil), "UpdateThingRes")
	proto.RegisterType((*DeleteThingReq)(nil), "DeleteThingReq")
	proto.RegisterType((*DeleteThingRes)(nil), "DeleteThingRes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RestService service

type RestServiceClient interface {
	GetThing(ctx context.Context, in *GetThingReq, opts ...grpc.CallOption) (*GetThingRes, error)
	CreateThing(ctx context.Context, in *CreateThingReq, opts ...grpc.CallOption) (*CreateThingRes, error)
	UpdateThing(ctx context.Context, in *UpdateThingReq, opts ...grpc.CallOption) (*UpdateThingRes, error)
	DeleteThing(ctx context.Context, in *DeleteThingReq, opts ...grpc.CallOption) (*DeleteThingRes, error)
}

type restServiceClient struct {
	cc *grpc.ClientConn
}

func NewRestServiceClient(cc *grpc.ClientConn) RestServiceClient {
	return &restServiceClient{cc}
}

func (c *restServiceClient) GetThing(ctx context.Context, in *GetThingReq, opts ...grpc.CallOption) (*GetThingRes, error) {
	out := new(GetThingRes)
	err := grpc.Invoke(ctx, "/RestService/GetThing", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restServiceClient) CreateThing(ctx context.Context, in *CreateThingReq, opts ...grpc.CallOption) (*CreateThingRes, error) {
	out := new(CreateThingRes)
	err := grpc.Invoke(ctx, "/RestService/CreateThing", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restServiceClient) UpdateThing(ctx context.Context, in *UpdateThingReq, opts ...grpc.CallOption) (*UpdateThingRes, error) {
	out := new(UpdateThingRes)
	err := grpc.Invoke(ctx, "/RestService/UpdateThing", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restServiceClient) DeleteThing(ctx context.Context, in *DeleteThingReq, opts ...grpc.CallOption) (*DeleteThingRes, error) {
	out := new(DeleteThingRes)
	err := grpc.Invoke(ctx, "/RestService/DeleteThing", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RestService service

type RestServiceServer interface {
	GetThing(context.Context, *GetThingReq) (*GetThingRes, error)
	CreateThing(context.Context, *CreateThingReq) (*CreateThingRes, error)
	UpdateThing(context.Context, *UpdateThingReq) (*UpdateThingRes, error)
	DeleteThing(context.Context, *DeleteThingReq) (*DeleteThingRes, error)
}

func RegisterRestServiceServer(s *grpc.Server, srv RestServiceServer) {
	s.RegisterService(&_RestService_serviceDesc, srv)
}

func _RestService_GetThing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetThingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestServiceServer).GetThing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RestService/GetThing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestServiceServer).GetThing(ctx, req.(*GetThingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestService_CreateThing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateThingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestServiceServer).CreateThing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RestService/CreateThing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestServiceServer).CreateThing(ctx, req.(*CreateThingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestService_UpdateThing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateThingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestServiceServer).UpdateThing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RestService/UpdateThing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestServiceServer).UpdateThing(ctx, req.(*UpdateThingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestService_DeleteThing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteThingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestServiceServer).DeleteThing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RestService/DeleteThing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestServiceServer).DeleteThing(ctx, req.(*DeleteThingReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _RestService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "RestService",
	HandlerType: (*RestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetThing",
			Handler:    _RestService_GetThing_Handler,
		},
		{
			MethodName: "CreateThing",
			Handler:    _RestService_CreateThing_Handler,
		},
		{
			MethodName: "UpdateThing",
			Handler:    _RestService_UpdateThing_Handler,
		},
		{
			MethodName: "DeleteThing",
			Handler:    _RestService_DeleteThing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rest.proto",
}

func init() { proto.RegisterFile("rest.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xc1, 0x6e, 0xd4, 0x30,
	0x10, 0x55, 0xd2, 0x26, 0x6d, 0x27, 0x28, 0x8b, 0x86, 0x82, 0xa2, 0x50, 0x60, 0xe5, 0x0b, 0xd5,
	0x8a, 0x3a, 0xed, 0x72, 0xeb, 0x0d, 0x5a, 0x84, 0xa8, 0x90, 0x2a, 0x05, 0xb8, 0x70, 0xf3, 0x6e,
	0x86, 0x10, 0xb4, 0xc4, 0x21, 0xf6, 0x2e, 0x12, 0x88, 0x0b, 0x9f, 0x00, 0x5f, 0xc2, 0xb7, 0xf0,
	0x0b, 0x7c, 0x08, 0xaa, 0x93, 0x46, 0x4e, 0x28, 0x52, 0xa5, 0x3d, 0x65, 0xe6, 0xe5, 0xcd, 0xf3,
	0x9b, 0x19, 0x1b, 0xa0, 0x26, 0xa5, 0x79, 0x55, 0x4b, 0x2d, 0xe3, 0xbd, 0x5c, 0xca, 0x7c, 0x41,
	0x89, 0xa8, 0x8a, 0x44, 0x94, 0xa5, 0xd4, 0x42, 0x17, 0xb2, 0x54, 0xed, 0xdf, 0x47, 0xe6, 0x33,
	0x3f, 0xc8, 0xa9, 0x3c, 0x50, 0x9f, 0x45, 0x9e, 0x53, 0x9d, 0xc8, 0xca, 0x30, 0xfe, 0x65, 0xb3,
	0x97, 0xe0, 0xbd, 0x7e, 0x5f, 0x94, 0x39, 0x86, 0xe0, 0x16, 0x59, 0xe4, 0x8c, 0x9d, 0xfd, 0x9d,
	0xd4, 0x2d, 0x32, 0x44, 0xd8, 0x2c, 0xc5, 0x47, 0x8a, 0x5c, 0x83, 0x98, 0x18, 0x1f, 0x80, 0x2f,
	0x67, 0x1f, 0x68, 0xae, 0xa3, 0xcd, 0xb1, 0xb3, 0x1f, 0x4c, 0xb7, 0xf8, 0xb9, 0x49, 0xd3, 0x16,
	0x66, 0x53, 0xf0, 0x1b, 0xa4, 0x2b, 0x77, 0xac, 0xf2, 0x5d, 0xf0, 0x56, 0x62, 0xb1, 0x6c, 0x34,
	0xbd, 0xb4, 0x49, 0xd8, 0x43, 0x08, 0x9e, 0x93, 0x36, 0x26, 0x52, 0xfa, 0x84, 0x11, 0x6c, 0xe9,
	0x8b, 0xf8, 0xc5, 0x69, 0x5b, 0x7b, 0x99, 0x32, 0xb2, 0x89, 0x0a, 0xef, 0x80, 0xaf, 0xb4, 0xd0,
	0x4b, 0x65, 0x78, 0x5e, 0xda, 0x66, 0x38, 0x86, 0x20, 0x23, 0x35, 0xaf, 0x0b, 0xd3, 0x73, 0xeb,
	0xdf, 0x86, 0x70, 0x0f, 0x3c, 0xa3, 0x19, 0x6d, 0x98, 0x2e, 0x7c, 0xde, 0x68, 0x36, 0x20, 0xe3,
	0x10, 0x9e, 0xd4, 0x24, 0x34, 0x75, 0x96, 0x3a, 0xbe, 0x73, 0x15, 0x3f, 0x1b, 0xf0, 0xd7, 0x71,
	0x66, 0x35, 0xbf, 0xd1, 0x6f, 0x9e, 0x43, 0xf8, 0xa6, 0xca, 0xae, 0xef, 0xea, 0x6c, 0xc0, 0x5f,
	0xc3, 0x15, 0x9b, 0x40, 0x78, 0x4a, 0x0b, 0xb2, 0xce, 0xfe, 0xff, 0x92, 0xce, 0x06, 0xdc, 0x35,
	0xce, 0x9d, 0xfe, 0x72, 0x21, 0x48, 0x49, 0xe9, 0x57, 0x54, 0xaf, 0x8a, 0x39, 0xe1, 0x09, 0x6c,
	0x5f, 0x5e, 0x00, 0xbc, 0xc1, 0xad, 0x4b, 0x13, 0xdb, 0x99, 0x62, 0x77, 0xbf, 0xff, 0xfe, 0xf3,
	0xd3, 0xbd, 0x8d, 0xb7, 0x92, 0xd5, 0x51, 0x62, 0xd0, 0xe4, 0x6b, 0xeb, 0xef, 0x1b, 0x3e, 0x83,
	0xc0, 0x5a, 0x17, 0x8e, 0x78, 0x7f, 0xd9, 0xf1, 0x00, 0x50, 0x6c, 0xd7, 0xa8, 0x85, 0x6c, 0xa7,
	0x53, 0x3b, 0x76, 0x26, 0x17, 0x32, 0xd6, 0x7c, 0x71, 0xc4, 0xfb, 0xdb, 0x89, 0x07, 0x40, 0x27,
	0x13, 0xf7, 0x65, 0xce, 0x21, 0xb0, 0xc6, 0x85, 0x23, 0xde, 0x1f, 0x74, 0x3c, 0x00, 0x14, 0xbb,
	0x6f, 0x64, 0xa2, 0xc9, 0x55, 0xbd, 0x1d, 0x3b, 0x93, 0xa7, 0xf7, 0x7e, 0x3c, 0xb9, 0x89, 0x21,
	0x78, 0x33, 0x29, 0xbf, 0xd0, 0xd4, 0x3b, 0xe4, 0x87, 0xfc, 0xe8, 0xed, 0xb6, 0x79, 0xeb, 0xb3,
	0xe5, 0xbb, 0x99, 0x6f, 0xa2, 0xc7, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x34, 0xba, 0x52,
	0x4f, 0x04, 0x00, 0x00,
}
